config/routes.rb
Rails.application.routes.draw do
  devise_for :members, :controllers => { registrations: 'registrations' }
  resources :owls
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "owls#index"
  get "members/profile"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :member
  belongs_to :owl
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :owls, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  
  
  
end

app/models/owl.rb
class Owl < ApplicationRecord
    belongs_to :member
    validates :owl, presence: true, length: {minimum:5, maximum:250}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController 

	private

	def sign_up_params 
		params.require(:member).permit(:name, :username, :email, :password, :password_confirmation)
	end

	def acount_update_params 
		params.require(:member).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
	end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController

    before_action :authenticate_member!

    def profile 
        @members = current_member
        @owls = Owl.all.order("created_at DESC")
    end 
end

app/controllers/owls_controller.rb
class OwlsController < ApplicationController
  before_action :set_owl, only: %i[ show edit update destroy ]
  before_action :authenticate_member!, except: [:index, :new]

  # GET /owls or /owls.json
  def index
    @owls = Owl.all.limit(5).order("created_at DESC")
    @owl =Owl.new
  end

  # GET /owls/1 or /owls/1.json
  def show
  end

  # GET /owls/new
  def new
    @owl = current_member.owls.build
  end

  # GET /owls/1/edit
  def edit
  end

  # POST /owls or /owls.json
  def create
    @owl = current_member.owls.build(owl_params)

    respond_to do |format|
      if @owl.save
        format.html { redirect_to root_path, notice: "Owl was successfully created." }
        format.json { render :show, status: :created, location: @owl }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @owl.errors, status: :unprocessable_entity }
      end
    end
  end

  

  # PATCH/PUT /owls/1 or /owls/1.json
  def update
    respond_to do |format|
      if @owl.update(owl_params)
        format.html { redirect_to owl_url(@owl), notice: "Owl was successfully updated." }
        format.json { render :show, status: :ok, location: @owl }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @owl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owls/1 or /owls/1.json
  def destroy
    @owl.destroy

    respond_to do |format|
      format.html { redirect_to owls_url, notice: "Owl was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owl
      @owl = Owl.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def owl_params
      params.require(:owl).permit(:owl)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owls_helper.rb
module OwlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Bookhouse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_tag "main" %>
    
  </head>
  
  <body>
  <% if notice %>
     <div class="flash alert">
       <p class="notification is-success"><%= notice %> <button class="delete"></button> </p>
      </div>
     <% end %>

     <% if alert %>
     <div class="flash">
     <p class="notification is-danger"><%= alert %></p>
       </div>
     <% end %>

     <nav class="navbar is-dark" id="stick">
        <div class="navbar-brand">
          <%= link_to root_path, class:"navbar-item" do %>
          <p class="title is-4 has-text-white" >Bookhouse</p>
          <% end %>
          <div class="navbar-burger burger" onclick="burguer()" onclick="burguerButtons()">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </div>
        </div>

        <div class="navbar-menu">
          <div class="navbar-start">
          
          </div>
          <div class="navbar-end">

            <% if member_signed_in? %>


            <div class="navbar-item">
              <div class="control">
                <%= link_to "New owl", new_owl_path, class:"button is-dark" %>
              </div>
            </div>

            <div class="navbar-item">
              <div class="control">
                <%= link_to current_member.name, members_profile_path , class:"button is-dark" %>
              </div>
            </div>
            
             
              
             

              

              
              <div class="navbar-item">
                <div class="control">
                  <%= link_to "Sign out", destroy_member_session_path, data: {turbo_method: :delete}, class:"button is-danger"%> 
                </div>
              </div>
             
                
             
            <% else %>

            <div class="navbar-item">
              <div class="control">
              <%= link_to "Sign in", new_member_session_path, class:"button is-success" %>
            </div>
            </div>

               

          
          <% end %>
            </div>
          </div>
        </div>
     
     </nav>

     


    <%= yield %>

    <script>
        // Step 1: Select all the delete buttons 
        // which are inside notification element 
        // and loop over them using forEach
        document.querySelectorAll(".notification .delete")
            .forEach(function ($deleteButton) {
  
                // Step 2: Get the parent notification 
                // of the delete button
                const parentNotification = $deleteButton.parentNode;
  
                // Add click event listener on delete 
                // button and when the button get clicked
                // remove the parent notification
                $deleteButton.addEventListener('click', function () {
                    parentNotification.parentNode
                        .removeChild(parentNotification);
                      }
                );
            });

            function burguer(){ 
           document.querySelector('.navbar-menu').classList.toggle('is-active')
            }

          
    </script>

  </body>
 
</html>

app/views/members/_member.html.erb
<div class="column is-2">
        <% if member_signed_in? %>
        <div class="title is-8"> <%= @members.name %></div>
            <%= link_to "Edit" %>
        </div>
    <% end %>

    

app/views/members/_owls.html.erb
<div class="column is-half is-centered">
<div>
                <p class="title is-4 is-danger">Your owls:</p>
                </div>
                <% @owls.each do |owl| %>
                 <% if owl.member.username == current_member.username %>
                  
                 
                       <div class="box">
                        <div class="media">
                            <div class="media-left">
                                <div class="image is-64x64">
                                    <img src="https://bulma.io/images/placeholders/64x64.png" alt="placeholder">
                                </div>
                                <div class="media-content">
                                    <div class="content">
                                        <strong> <%= owl.member.name %> </strong> <br>
                    
                    <small><%= owl.member.username %></small> <br>
                   
                    <p> <%= owl.owl %></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                       </div>
                      
                            
                        <% end %>
                        <% end %>
             </div>

app/views/members/profile.html.erb
     <div class="section">
    <div class="container">
        <div class="columns">

        

            <%= render "member" %>
            <%= render "owls" %>
           

        </div>
    </div>
</div>

   
             
                    
               
        

       
        
       

app/views/owls/_feed.html.erb
<div class="column is-half is-centered">
    <% if member_signed_in? %>
    <article class="media box">
            <div class="media-left">
                <figure class="image is-64x64">
                 <img src="https://bulma.io/images/placeholders/64x64.png" alt="placeholder">
                </figure>
            </div>

        <div class="media-content">
            <%= render 'form' %>
        </div>
    </article>

    <% end %>

<% @owls.each do |owl| %>
    <div class="box">
       <article class="media">
            <div class="media-left">
            <figure class="image is-64x64">
            <img src="https://bulma.io/images/placeholders/64x64.png" alt="placeholder">
            </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <% if member_signed_in? %>
                    <strong> <%= owl.member.name %> </strong> <br>
                    
                    <small><%= owl.member.username %></small> <br>
                   <% end %>
                    <p> <%= owl.owl %></p>
                </div>
                <nav class="level">
                    <div class="level-left is-mobile">
                    <% if signed_in? %>
                    <%  if owl.member_id == current_member.id %>
                        <%= link_to owl, class: "item" do  %>
                            <span class="icon"><i class="fa fa-link" aria-hidden="true"></i> </span>
                        <% end %>
                        <%= link_to edit_owl_path(owl), class: "item" do %>
                            <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i> </span>
                        <% end %>

                        
                        <%= link_to owl, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete it?" } do %>
                            <span class="icon"> <i class="fa fa-trash" aria-hidden="true"></i> </span>
                           <% end %>
                            <% end %>
                        <% end %>
                    </div> 
                </nav>
            </div>
        </article>
    </div>
<% end  %>
</div>

app/views/owls/_form.html.erb
<%= simple_form_for (@owl) do |form| %>
  <% if @owl.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(owl.errors.count, "error") %> prohibited this owl from being saved:</h2>

      <ul>
        <% owl.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
 
    <%= form.text_area :owl, autofocus: true, placeholder:"What did you see?", class:"textarea is-medium " %>
  </div>

  <div class="column new">
  <div>
    <%= form.submit class:"button is-dark" %>
  </div>
  </div>
  
<% end %>

app/views/owls/_news.html.erb
<div class="column is-one-quarter">
    
    <div class="panel is-danger">
        <div class="panel-heading">
           <div class=" is-center">What the log is saying...</div> 
        </div>

            <% if @owls.count > 0 %>
            <% @owls.each do |owl| %>
        <div class="panel-block">
    
             <%= link_to owl.owl, owl %>

        </div>
        <% end  %>

        <% else %>

        <div class="panel-block">   
        <div class="notification is-light is-warning">
            The log does not have anything to say today.
        </div>
        </div>
        <% end %>
    </div>
    
</div>

app/views/owls/_owl.html.erb
    <div id="<%= dom_id owl %>">

      <p>
        <strong class="title is-4"><%= owl.member.name %>:</strong>
        <%= owl.owl %>
      </p>

    </div>

app/views/owls/_popular.html.erb
<div class="column is-one-quarter">
    <nav class="panel">
        <p class="panel-heading">Members to follow</p>
        
        <% @members = Member.all %>
        <% @members.limit(5).each do |m| %>
        <% if signed_in? %>
        <div class="panel-block">
            <%= link_to m.email%>
        </div>
        <% else %>
        <div class="panel-block">
            <p>...</p>
        </div>
        <% end %>
    <% end %>
    </nav>
</div>

app/views/owls/edit.html.erb
<div class="section">
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-6">
          <h1 class="title is-4">Editing owl</h1>

<%= render "form", owl: @owl %>

<br>

<div>
  <%= link_to "Show this owl", @owl %> |
  <%= link_to "Back to owls", owls_path %>
</div>
          </div>
        </div>
    </div>
</div>

app/views/owls/index.html.erb
<div class="section">
    <div class="container">
        <div class="columns">


            <%= render 'news' %>
            <%= render 'feed' %>
            <%= render 'popular' %>

        </div>
    </div>
</div>

app/views/owls/new.html.erb
<div class="section">
  <div class="container">
  <div class="column is-centered">
  <h1 class="title has-text-centered">New owl</h1>

<%= render "form", owl: @owl %>

<br>

<div>
  <%= link_to "Back to the Bookhouse", owls_path %>
</div>

</div>
</div>
</div>

app/views/owls/show.html.erb
<div class="section">
  <div class="container">
  <div class="column is-centered">
  <h1 class="title has-text-centered">Edit owl</h1>

  <%= render @owl %>
<div>
  <% if  current_member.id == @owl.member.id %>
  <%= link_to "Edit this owl", edit_owl_path(@owl) %>
  <%= link_to "Back to owls", owls_path %>

  <%= button_to "Destroy this owl", @owl, method: :delete %>
  <% end %>

</div>


</div>
</div>
</div>